[package]
name = "motdyn"
version = "1.0.2"
edition = "2021"
description = "🛠️ motdyn (Dynamic MOTD): Rust-powered and highly configurable for real-time login insights."
license = "MIT"
authors = ["lvillis<lvillis@outlook.com>"]
repository = "https://github.com/lvillis/motdyn"
homepage = "https://github.com/lvillis/motdyn"
documentation = "https://github.com/lvillis/motdyn/blob/main/README.md"
exclude = [
    "/docs/",
    "/tests/",
    "/.config/",
    "/.github/",
    "/.justfile",
    "/rust-toolchain.toml",
    "/.gitignore",
]

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
chrono = "0.4"
colored = "2.0"
libc = "0.2.169"
toml = "0.8.19"
serde = { version = "1.0.216", features = ["derive"] }
reqwest = { version = "0.12.9", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[package.metadata.release]
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
pre-release-commit-message = "chore: release {{crate_name}} version {{version}}"
tag-message = "chore: release {{crate_name}} version {{version}}"
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
