use std::error::Error;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

pub fn do_install() -> Result<(), Box<dyn Error>> {
    let profile_dir = "/etc/profile.d";
    if !Path::new(profile_dir).exists() {
        return Err(format!(
            "Directory '{}' not found, cannot install system-wide script.",
            profile_dir
        )
        .into());
    }

    let script_path = format!("{}/motdyn.sh", profile_dir);
    let mut file = File::create(&script_path)?;

    writeln!(
        file,
        "#!/bin/sh\n# This script is auto-generated by 'motdyn install'.\n# It will run 'motdyn' on login.\nif [ -x \"$(command -v motdyn)\" ]; then\n    motdyn\nfi\n"
    )?;

    #[cfg(unix)]
    {
        let mut perms = file.metadata()?.permissions();
        perms.set_mode(0o755);
        file.set_permissions(perms)?;
    }

    Ok(())
}

pub fn do_uninstall() -> Result<(), Box<dyn Error>> {
    let script_path = "/etc/profile.d/motdyn.sh";
    if Path::new(script_path).exists() {
        fs::remove_file(script_path)?;
    }
    Ok(())
}

pub fn do_status() -> Result<(), Box<dyn Error>> {
    let script_path = "/etc/profile.d/motdyn.sh";
    if Path::new(script_path).exists() {
        println!(
            "The system IS installed with motdyn script at {}",
            script_path
        );
    } else {
        println!(
            "The system is NOT installed with motdyn (no {}).",
            script_path
        );
    }
    Ok(())
}
