use std::env;
use std::fmt;
use std::fs::{self, File};
use std::io;
use std::io::Write;
use std::path::{Path, PathBuf};

use clap::ValueEnum;

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

const SYSTEM_SCRIPT_PATH: &str = "/etc/profile.d/motdyn.sh";
const DEFAULT_USER_PROFILE_PATH: &str = ".profile";
const USER_PROFILE_FILES: &[&str] = &[
    DEFAULT_USER_PROFILE_PATH,
    ".bash_profile",
    ".bash_login",
    ".zprofile",
];
const USER_GUARD_ENV: &str = "MOTDYN_LOGIN_HOOK_RAN";
const USER_BLOCK_START: &str = "# >>> motdyn >>>";
const USER_BLOCK_END: &str = "# <<< motdyn <<<";

type Result<T> = std::result::Result<T, InstallerError>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum UserProfileTarget {
    #[value(name = "profile")]
    Profile,
    #[value(name = "bash_profile")]
    BashProfile,
    #[value(name = "bash_login")]
    BashLogin,
    #[value(name = "zprofile")]
    Zprofile,
}

impl UserProfileTarget {
    fn filename(self) -> &'static str {
        match self {
            Self::Profile => ".profile",
            Self::BashProfile => ".bash_profile",
            Self::BashLogin => ".bash_login",
            Self::Zprofile => ".zprofile",
        }
    }
}

#[derive(Debug)]
pub enum InstallerError {
    TargetRequiresUserMode,
    MissingSystemProfileDir(PathBuf),
    MissingHome,
    IncompleteManagedBlock(PathBuf),
    Io {
        action: &'static str,
        path: PathBuf,
        source: io::Error,
    },
}

impl fmt::Display for InstallerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TargetRequiresUserMode => {
                write!(f, "`--target` is only supported together with `--user`")
            }
            Self::MissingSystemProfileDir(path) => write!(
                f,
                "directory '{}' not found, cannot install system-wide script",
                path.display()
            ),
            Self::MissingHome => {
                write!(f, "HOME is not set, cannot resolve user profile path")
            }
            Self::IncompleteManagedBlock(path) => write!(
                f,
                "detected incomplete motdyn managed block in '{}'; clean it up manually first",
                path.display()
            ),
            Self::Io {
                action,
                path,
                source,
            } => write!(f, "failed to {} '{}': {}", action, path.display(), source),
        }
    }
}

impl std::error::Error for InstallerError {}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum UserBlockState {
    Missing,
    Complete,
    Incomplete,
}

pub fn do_install(user: bool, target: Option<UserProfileTarget>) -> Result<()> {
    if user {
        install_user(target)
    } else {
        if target.is_some() {
            return Err(InstallerError::TargetRequiresUserMode);
        }
        install_system()
    }
}

pub fn do_uninstall(user: bool, target: Option<UserProfileTarget>) -> Result<()> {
    if user {
        uninstall_user(target)
    } else {
        if target.is_some() {
            return Err(InstallerError::TargetRequiresUserMode);
        }
        uninstall_system()
    }
}

pub fn do_status(user: bool, target: Option<UserProfileTarget>) -> Result<()> {
    if user {
        print_user_status(target)?;
    } else {
        if target.is_some() {
            return Err(InstallerError::TargetRequiresUserMode);
        }
        print_system_status();
        print_user_status(None)?;
    }
    Ok(())
}

fn install_system() -> Result<()> {
    let profile_dir = Path::new("/etc/profile.d");
    if !profile_dir.exists() {
        return Err(InstallerError::MissingSystemProfileDir(
            profile_dir.to_path_buf(),
        ));
    }

    let mut file = File::create(SYSTEM_SCRIPT_PATH)
        .map_err(|err| io_error("create system install script", SYSTEM_SCRIPT_PATH, err))?;

    writeln!(
        file,
        "#!/bin/sh\n# This script is auto-generated by 'motdyn install'.\n# It will run 'motdyn' on interactive login shells.\n# motdyn failures must never block or abort login.\nif [ -z \"${{{guard_env}:-}}\" ]; then\n    export {guard_env}=1\n    case \"$-\" in\n        *i*)\n            if command -v motdyn >/dev/null 2>&1; then\n                motdyn --compact || :\n            fi\n            ;;\n    esac\nfi\n",
        guard_env = USER_GUARD_ENV,
    )
    .map_err(|err| io_error("write system install script", SYSTEM_SCRIPT_PATH, err))?;

    #[cfg(unix)]
    {
        let mut perms = file
            .metadata()
            .map_err(|err| {
                io_error(
                    "read system install script metadata",
                    SYSTEM_SCRIPT_PATH,
                    err,
                )
            })?
            .permissions();
        perms.set_mode(0o755);
        file.set_permissions(perms).map_err(|err| {
            io_error(
                "set system install script permissions",
                SYSTEM_SCRIPT_PATH,
                err,
            )
        })?;
    }

    Ok(())
}

fn install_user(target: Option<UserProfileTarget>) -> Result<()> {
    let home = user_home_dir()?;
    let targets = resolve_user_targets(&home, target)?;
    let mut planned_updates = Vec::new();

    for profile_path in targets {
        let existing = read_optional_text_file(&profile_path)?;
        if classify_user_block(&existing) == UserBlockState::Incomplete {
            return Err(InstallerError::IncompleteManagedBlock(profile_path));
        }
        planned_updates.push((profile_path, existing));
    }

    for (profile_path, existing) in planned_updates {
        let updated = upsert_user_block(&existing);
        if let Some(parent) = profile_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| io_error("create profile directory", parent, err))?;
        }
        fs::write(&profile_path, updated)
            .map_err(|err| io_error("write user profile", &profile_path, err))?;
    }

    Ok(())
}

fn uninstall_system() -> Result<()> {
    if Path::new(SYSTEM_SCRIPT_PATH).exists() {
        fs::remove_file(SYSTEM_SCRIPT_PATH)
            .map_err(|err| io_error("remove system install script", SYSTEM_SCRIPT_PATH, err))?;
    }
    Ok(())
}

fn uninstall_user(target: Option<UserProfileTarget>) -> Result<()> {
    let home = user_home_dir()?;
    let mut planned_updates = Vec::new();

    for profile_path in resolve_user_targets(&home, target)? {
        if !profile_path.exists() {
            continue;
        }

        let existing = fs::read_to_string(&profile_path)
            .map_err(|err| io_error("read user profile", &profile_path, err))?;
        if classify_user_block(&existing) == UserBlockState::Incomplete {
            return Err(InstallerError::IncompleteManagedBlock(profile_path));
        }

        let (updated, removed) = remove_user_block(&existing);
        if removed {
            planned_updates.push((profile_path, updated));
        }
    }

    for (profile_path, updated) in planned_updates {
        fs::write(&profile_path, updated)
            .map_err(|err| io_error("write user profile", &profile_path, err))?;
    }
    Ok(())
}

fn print_system_status() {
    if Path::new(SYSTEM_SCRIPT_PATH).exists() {
        println!("System install: present at {}", SYSTEM_SCRIPT_PATH);
    } else {
        println!(
            "System install: not present (expected {}).",
            SYSTEM_SCRIPT_PATH
        );
    }
}

fn print_user_status(target: Option<UserProfileTarget>) -> Result<()> {
    let home = user_home_dir()?;
    let checked_paths = resolve_user_targets(&home, target)?;
    let mut installed_paths = Vec::new();
    let mut invalid_paths = Vec::new();

    for profile_path in &checked_paths {
        let content = match fs::read_to_string(profile_path) {
            Ok(content) => content,
            Err(err) if err.kind() == io::ErrorKind::NotFound => continue,
            Err(err) => return Err(io_error("read user profile", profile_path, err)),
        };

        match classify_user_block(&content) {
            UserBlockState::Complete => installed_paths.push(profile_path.display().to_string()),
            UserBlockState::Incomplete => invalid_paths.push(profile_path.display().to_string()),
            UserBlockState::Missing => {}
        }
    }

    if !installed_paths.is_empty() {
        println!("User install: present in {}", installed_paths.join(", "));
    } else {
        println!(
            "User install: not present (checked {}).",
            checked_paths
                .iter()
                .map(|path| path.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    if !invalid_paths.is_empty() {
        println!(
            "User install: invalid managed block in {}",
            invalid_paths.join(", ")
        );
    }

    Ok(())
}

fn user_home_dir() -> Result<PathBuf> {
    let home = env::var_os("HOME").ok_or(InstallerError::MissingHome)?;
    Ok(PathBuf::from(home))
}

fn user_profile_paths(home: &Path) -> Vec<PathBuf> {
    USER_PROFILE_FILES
        .iter()
        .map(|name| home.join(name))
        .collect()
}

fn resolve_user_targets(home: &Path, target: Option<UserProfileTarget>) -> Result<Vec<PathBuf>> {
    match target {
        Some(value) => Ok(vec![resolve_user_target_path(home, value)?]),
        None => Ok(user_install_targets(home)),
    }
}

fn resolve_user_target_path(home: &Path, target: UserProfileTarget) -> Result<PathBuf> {
    Ok(home.join(target.filename()))
}

fn user_install_targets(home: &Path) -> Vec<PathBuf> {
    let default_path = home.join(DEFAULT_USER_PROFILE_PATH);
    let mut targets = Vec::new();

    for path in user_profile_paths(home) {
        if path.exists() {
            targets.push(path);
        }
    }

    if !targets.iter().any(|path| path == &default_path) {
        targets.insert(0, default_path);
    }

    targets
}

fn user_install_block() -> &'static str {
    concat!(
        "# >>> motdyn >>>\n",
        "# This block is auto-generated by 'motdyn install --user'.\n",
        "# It is guarded so motdyn only runs once even if multiple login profiles source each other.\n",
        "# motdyn failures must never block or abort login.\n",
        "if [ -z \"${MOTDYN_LOGIN_HOOK_RAN:-}\" ]; then\n",
        "    export MOTDYN_LOGIN_HOOK_RAN=1\n",
        "    case \"$-\" in\n",
        "        *i*)\n",
        "            if command -v motdyn >/dev/null 2>&1; then\n",
        "                motdyn --compact || :\n",
        "            fi\n",
        "            ;;\n",
        "    esac\n",
        "fi\n",
        "# <<< motdyn <<<\n"
    )
}

fn classify_user_block(content: &str) -> UserBlockState {
    let mut in_block = false;
    let mut block_count = 0;

    for line in content.lines() {
        if line == USER_BLOCK_START {
            if in_block {
                return UserBlockState::Incomplete;
            }
            in_block = true;
            continue;
        }

        if line == USER_BLOCK_END {
            if !in_block {
                return UserBlockState::Incomplete;
            }
            in_block = false;
            block_count += 1;
        }
    }

    if in_block {
        UserBlockState::Incomplete
    } else if block_count > 0 {
        UserBlockState::Complete
    } else {
        UserBlockState::Missing
    }
}

fn upsert_user_block(existing: &str) -> String {
    let (mut cleaned, _) = remove_user_block(existing);
    if !cleaned.is_empty() && !cleaned.ends_with('\n') {
        cleaned.push('\n');
    }
    if !cleaned.is_empty() {
        cleaned.push('\n');
    }
    cleaned.push_str(user_install_block());
    cleaned
}

fn remove_user_block(existing: &str) -> (String, bool) {
    let mut kept_lines = Vec::new();
    let mut removed = false;
    let lines: Vec<&str> = existing.lines().collect();
    let mut idx = 0;

    while idx < lines.len() {
        if lines[idx] == USER_BLOCK_START {
            if let Some(end_offset) = lines[idx + 1..]
                .iter()
                .position(|line| *line == USER_BLOCK_END)
            {
                idx += end_offset + 2;
                removed = true;
                continue;
            }

            kept_lines.extend_from_slice(&lines[idx..]);
            break;
        }
        kept_lines.push(lines[idx]);
        idx += 1;
    }

    let mut cleaned = kept_lines.join("\n");
    while cleaned.ends_with("\n\n") {
        cleaned.pop();
    }
    if !cleaned.is_empty() {
        cleaned.push('\n');
    }
    (cleaned, removed)
}

fn read_optional_text_file(path: &Path) -> Result<String> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(content),
        Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(String::new()),
        Err(err) => Err(io_error("read user profile", path, err)),
    }
}

fn io_error(action: &'static str, path: impl AsRef<Path>, source: io::Error) -> InstallerError {
    InstallerError::Io {
        action,
        path: path.as_ref().to_path_buf(),
        source,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upsert_user_block_replaces_existing_block() {
        let existing = format!(
            "line 1\n{}\nold\n{}\nline 2\n",
            USER_BLOCK_START, USER_BLOCK_END
        );
        let updated = upsert_user_block(&existing);

        assert_eq!(updated.matches(USER_BLOCK_START).count(), 1);
        assert_eq!(updated.matches(USER_BLOCK_END).count(), 1);
        assert!(updated.contains("line 1"));
        assert!(updated.contains("line 2"));
        assert!(!updated.contains("\nold\n"));
    }

    #[test]
    fn remove_user_block_drops_only_managed_lines() {
        let existing = format!(
            "before\n{}\nauto\n{}\nafter\n",
            USER_BLOCK_START, USER_BLOCK_END
        );
        let (cleaned, removed) = remove_user_block(&existing);

        assert!(removed);
        assert_eq!(cleaned, "before\nafter\n");
    }

    #[test]
    fn remove_user_block_preserves_unterminated_block() {
        let existing = format!("before\n{}\nauto\nafter\n", USER_BLOCK_START);
        let (cleaned, removed) = remove_user_block(&existing);

        assert!(!removed);
        assert_eq!(cleaned, existing);
    }

    #[test]
    fn classify_user_block_detects_incomplete_markers() {
        assert_eq!(
            classify_user_block(USER_BLOCK_START),
            UserBlockState::Incomplete
        );
        assert_eq!(
            classify_user_block(USER_BLOCK_END),
            UserBlockState::Incomplete
        );
        assert_eq!(
            classify_user_block(&format!("{}\n{}\n", USER_BLOCK_START, USER_BLOCK_END)),
            UserBlockState::Complete
        );
    }

    #[test]
    fn user_install_targets_include_profile_and_existing_shell_profiles() {
        let home = tempfile::tempdir().unwrap();
        fs::write(home.path().join(".bash_profile"), "existing").unwrap();
        fs::write(home.path().join(".zprofile"), "existing").unwrap();

        let targets = user_install_targets(home.path());
        let target_names = targets
            .iter()
            .map(|path| path.file_name().unwrap().to_string_lossy().to_string())
            .collect::<Vec<_>>();

        assert!(target_names.contains(&".profile".to_string()));
        assert!(target_names.contains(&".bash_profile".to_string()));
        assert!(target_names.contains(&".zprofile".to_string()));
        assert!(!target_names.contains(&".bash_login".to_string()));
    }

    #[test]
    fn resolve_user_target_path_accepts_known_targets() {
        let home = tempfile::tempdir().unwrap();

        assert_eq!(
            resolve_user_target_path(home.path(), UserProfileTarget::Profile).unwrap(),
            home.path().join(".profile")
        );
        assert_eq!(
            resolve_user_target_path(home.path(), UserProfileTarget::BashProfile).unwrap(),
            home.path().join(".bash_profile")
        );
    }

    #[test]
    fn user_install_block_sets_guard_env() {
        let block = user_install_block();

        assert!(block.contains(USER_GUARD_ENV));
        assert!(block.contains("if [ -z"));
        assert!(block.contains("export MOTDYN_LOGIN_HOOK_RAN=1"));
        assert!(block.contains("motdyn --compact || :"));
    }

    #[test]
    fn user_profile_target_returns_expected_filename() {
        assert_eq!(UserProfileTarget::Profile.filename(), ".profile");
        assert_eq!(UserProfileTarget::BashProfile.filename(), ".bash_profile");
        assert_eq!(UserProfileTarget::BashLogin.filename(), ".bash_login");
        assert_eq!(UserProfileTarget::Zprofile.filename(), ".zprofile");
    }
}
